#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : argon2
Version  : 20190702
Release  : 8
URL      : https://github.com/P-H-C/phc-winner-argon2/archive/20190702/phc-winner-argon2-20190702.tar.gz
Source0  : https://github.com/P-H-C/phc-winner-argon2/archive/20190702/phc-winner-argon2-20190702.tar.gz
Summary  : Development libraries for libargon2
Group    : Development/Tools
License  : CC0-1.0
Requires: argon2-bin = %{version}-%{release}
Requires: argon2-lib = %{version}-%{release}
Requires: argon2-license = %{version}-%{release}

%description
# Argon2
[![Build Status](https://travis-ci.org/P-H-C/phc-winner-argon2.svg?branch=master)](https://travis-ci.org/P-H-C/phc-winner-argon2)
[![Build status](https://ci.appveyor.com/api/projects/status/8nfwuwq55sgfkele?svg=true)](https://ci.appveyor.com/project/P-H-C/phc-winner-argon2)
[![codecov.io](https://codecov.io/github/P-H-C/phc-winner-argon2/coverage.svg?branch=master)](https://codecov.io/github/P-H-C/phc-winner-argon2?branch=master)

%package bin
Summary: bin components for the argon2 package.
Group: Binaries
Requires: argon2-license = %{version}-%{release}

%description bin
bin components for the argon2 package.


%package dev
Summary: dev components for the argon2 package.
Group: Development
Requires: argon2-lib = %{version}-%{release}
Requires: argon2-bin = %{version}-%{release}
Provides: argon2-devel = %{version}-%{release}
Requires: argon2 = %{version}-%{release}

%description dev
dev components for the argon2 package.


%package lib
Summary: lib components for the argon2 package.
Group: Libraries
Requires: argon2-license = %{version}-%{release}

%description lib
lib components for the argon2 package.


%package license
Summary: license components for the argon2 package.
Group: Default

%description license
license components for the argon2 package.


%prep
%setup -q -n phc-winner-argon2-20190702
cd %{_builddir}/phc-winner-argon2-20190702

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605310760
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  OPTTARGET=westmere LIBRARY_REL=lib64


%install
export SOURCE_DATE_EPOCH=1605310760
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/argon2
cp %{_builddir}/phc-winner-argon2-20190702/LICENSE %{buildroot}/usr/share/package-licenses/argon2/edffb32348c3b38dd68cfb2e6cac9dc4a3502c8b
%make_install LIBRARY_REL=lib64

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/argon2

%files dev
%defattr(-,root,root,-)
/usr/include/argon2.h
/usr/lib64/libargon2.so
/usr/lib64/pkgconfig/libargon2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libargon2.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/argon2/edffb32348c3b38dd68cfb2e6cac9dc4a3502c8b
