#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : argon2
Version  : 20171227
Release  : 4
URL      : https://github.com/P-H-C/phc-winner-argon2/archive/20171227.tar.gz
Source0  : https://github.com/P-H-C/phc-winner-argon2/archive/20171227.tar.gz
Summary  : Development libraries for libargon2
Group    : Development/Tools
License  : CC0-1.0
Requires: argon2-bin = %{version}-%{release}
Requires: argon2-lib = %{version}-%{release}
Requires: argon2-license = %{version}-%{release}

%description
# Argon2
[![Build Status](https://travis-ci.org/P-H-C/phc-winner-argon2.svg?branch=master)](https://travis-ci.org/P-H-C/phc-winner-argon2)
[![Build status](https://ci.appveyor.com/api/projects/status/8nfwuwq55sgfkele?svg=true)](https://ci.appveyor.com/project/P-H-C/phc-winner-argon2)
[![codecov.io](https://codecov.io/github/P-H-C/phc-winner-argon2/coverage.svg?branch=master)](https://codecov.io/github/P-H-C/phc-winner-argon2?branch=master)

%package bin
Summary: bin components for the argon2 package.
Group: Binaries
Requires: argon2-license = %{version}-%{release}

%description bin
bin components for the argon2 package.


%package dev
Summary: dev components for the argon2 package.
Group: Development
Requires: argon2-lib = %{version}-%{release}
Requires: argon2-bin = %{version}-%{release}
Provides: argon2-devel = %{version}-%{release}

%description dev
dev components for the argon2 package.


%package lib
Summary: lib components for the argon2 package.
Group: Libraries
Requires: argon2-license = %{version}-%{release}

%description lib
lib components for the argon2 package.


%package license
Summary: license components for the argon2 package.
Group: Default

%description license
license components for the argon2 package.


%prep
%setup -q -n phc-winner-argon2-20171227

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544633378
make  %{?_smp_mflags} OPTTARGET=westmere


%install
export SOURCE_DATE_EPOCH=1544633378
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/argon2
cp LICENSE %{buildroot}/usr/share/package-licenses/argon2/LICENSE
%make_install
## install_append content
mv %{buildroot}/usr/lib %{buildroot}/usr/lib64
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/argon2

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libargon2.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libargon2.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/argon2/LICENSE
